### ISSUE TITLE
[P1-Unsafe Int] unchecked_sub

### ISSUE THREAD

**Issue by rajathkotyal** [rajathkotyal/verify-rust-std#2]
[Official Repo Tracking Issue](https://github.com/model-checking/verify-rust-std/issues/59)

Tasks :

1. Set up the necessary environment.
2. Write individual proofs for verifying the absence of arithmetic overflow/underflow and undefined behavior for all integer types: i8, i16, i32, i64, i128, u8, u16, u32, u64, u128.
3. Add proofs into a dedicated file.
  a. For example, `library/core/src/num/mod.rs` --> This will contain all proofs for unchecked_add/del/sub, etc. 
4. Please make sure not to modify other people's code, since we will be co-working on the same files. Avoid code conflicts as much as possible. **Pull code every time a merge is made.**

IMP: comment with the branch name you will be working on, with its link.

Ref: https://github.com/rajathkotyal/verify-rust-std/blob/main/doc/src/challenges/0011-floats-ints.md

**Comment by Yenyun035** [comment]
Merged in PR#96.
